### ISSUE TITLE
Missing Examples HTTP build/load setup.

### ISSUE THREAD

**Issue by GordanRamsay** [Unity-Technologies/Addressables-Sample#13]
Hi, I followed 
https://docs.unity3d.com/Packages/com.unity.addressables@0.4/manual/AddressableAssetsHostingServices.html
to the word. But I'm unable to get this working with a server running on the local machine.
Exception encountered in operation Resource<IAssetBundleResource>(editorhostedpacks_assets_all_3fc51f1662e9e7ea337ef78d2a947322.bundle): RemoteAssetBundleProvider unable to load from url http://162.17.216.37:62868/editorhostedpacks_assets_all_3fc51f1662e9e7ea337ef78d2a947322.bundle, result='Cannot connect to destination host'.

Please add an example for HTTP setup.

**Comment by alffanclub** [comment]
Apologies for the slow response, but three notes...
1. for general issues, please post to the forums, as you'll get a much quicker response: https://forum.unity.com/forums/addressables.156/
2. we've looked into the HTTP example, and it's difficult to make one that would simply work on download due to the complexities of getting the proper IP address setup.  We haven't totally given up on it, but it's unlikely to be out soon. 
3. even in July when you posted this, those docs (0.4) were very out of date.  Unfortunately, google will always return old docs.  I'd recommend starting with https://docs.unity3d.com/Packages/com.unity.addressables@latest and making sure you are using the latest package at all times.
